config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'

  get 'using-from-example/without-from', to: 'using_from_example#without_from'
  get 'using-from-example/with-from',    to: 'using_from_example#with_from'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :products
end

app/models/inbound_log.rb
class InboundLog < ApplicationRecord
  belongs_to :inbound_order
  belongs_to :shelf

  # If common order log is going to be extracted to a concern for other order types to use it,
  # this is the stuff you'll want on it:
  belongs_to :product, required: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  scope :without_shelf, -> { where shelf_id: nil }
end

app/models/inbound_order.rb
class InboundOrder < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries
  has_many :inbound_order_transitions, autosave: false

  has_many :inbound_logs, inverse_of: :inbound_order
  has_many :inbound_shelves, through: :inbound_logs, source: :shelf

  def state_machine
    @state_machine ||= InboundOrderStateMachine.new self, transition_class: InboundOrderTransition
  end
  delegate :current_state, :trigger, :available_events, to: :state_machine

  def received?
    current_state == "received"
  end

  def pending?
    current_state == "pending"
  end

  def completed?
    current_state == "completed"
  end

  def store_items!
    InboundInventoryStorer.new(self).store_order_items!
  end

  class << self
    private

    def transition_class
      InboundOrderTransition
    end

    def initial_state
      :pending
    end
  end
end

app/models/inbound_order_transition.rb
class InboundOrderTransition < ActiveRecord::Base
  belongs_to :inbound_order, inverse_of: :inbound_order_transitions

  after_destroy :update_most_recent, if: :most_recent?

  private

  def update_most_recent
    last_transition = inbound_order.inbound_order_transitions.order(:sort_key).last
    return unless last_transition.present?
    last_transition.update_column(:most_recent, true)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :inbound_log

  belongs_to :product
  has_one :category, through: :product

  belongs_to :shelf, optional: true

  # I use `define_method` for short, one-liner methods :) Sue me if you don't like it.
  define_method(:available?) { shelf.any? }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :brand, presence: true
  validates :name, uniqueness: { scope: :brand }
  belongs_to :category
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :items, inverse_of: :shelf
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/using_from_example_controller.rb
class UsingFromExampleController < ApplicationController
  include ItemFiltering
  helper_method :item_filter_params

  def without_from
    @items = requested_scope(Item.all).limit(2000).includes(:product, :category, :shelf)
  end

  def with_from
    @items = Item.from(requested_scope(Item.all).limit(2000), :items)
                 .includes(:product, :category, :shelf)
  end

  private

  def requested_scope(starting_scope)
    scoping_methods = [:filter_and_sort_by_product, :filter_and_sort_by_category]
    scoping_methods.reduce(starting_scope) { |scope, scoping_method| send scoping_method, scope }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_filtering.rb
module ItemFiltering
  def item_filter_params
    @item_filter_params ||= params.permit :id,
                                          :category_id,   :category_id_sort,
                                          :category_name, :category_name_sort,
                                          :product_id,    :product_id_sort,
                                          :product_name,  :product_name_sort
  end

  def filter_by_category?
    filter_by? :category, :id, :name
  end

  def sort_by_category?
    sort_by? :category, :id, :name
  end

  def category_scope
    Category.where conditions_from_params(:category, :id, :name)
  end

  def filter_and_sort_by_category(scope)
    return scope unless filter_by_category? || sort_by_category?
    scope = filter_by_category scope.joins(:category)
    sort_by_category scope
  end

  def filter_by_product?
    (params.keys & [:product_id, :product_name]).any?
  end

  def sort_by_product?
    sort_by? :product, :id, :name
  end

  def product_scope
    Product.where conditions_from_params(:product, :id, :name)
  end

  def filter_and_sort_by_product(scope)
    return scope unless filter_by_product?
    scope = filter_by_product scope.joins(:product)
    sort_by_product scope
  end

  def filter_by_shelf?
    filter_by? :shelf, :id, :name
  end

  def sort_by_shelf?
    sort_by? :shelf, :id, :name
  end

  def shelf_scope
    Shelf.where conditions_from_params(:shelf, :id, :name)
  end

  def filter_and_sort_by_shelf(scope)
    return scope unless filter_by_shelf? || sort_by_shelf?
    scope = filter_by_shelf scope.joins(:shelf)
    sort_by_shelf scope
  end

  private

  def filter_by_category(scope)
    return scope unless filter_by_category?
    scope.merge(category_scope)
  end

  def sort_by_category(scope)
    return scope unless sort_by_category?
    scope.order sort_conditions_from_params(:category, :id, :name)
  end

  def filter_by_product(scope)
    return scope unless filter_by_product?
    scope.merge(product_scope)
  end

  def sort_by_product(scope)
    return scope unless sort_by_product?
    scope.order sort_conditions_from_params(:product, :id, :name)
  end

  def filter_by_shelf(scope)
    return scope unless filter_by_shelf?
    scope.merge(shelf_scope)
  end

  def sort_by_shelf(scope)
    return scope unless sort_by_shelf?
    scope.order sort_conditions_from_params(:shelf, :id, :name)
  end

  def sort_by?(assoc_name, *assoc_attrs)
    sort_keys(assoc_name, assoc_attrs).reduce(false) do |must_sort, sort_key|
      must_sort || params.key?(sort_key) && params[sort_key].in?(%(asc desc))
    end
  end

  def sort_keys(assoc_name, assoc_attrs)
    assoc_attrs.map { |attr_name| "#{assoc_name}_#{attr_name}_sort".to_sym }
  end

  def filter_by?(assoc_name, *assoc_attrs)
    (params.keys & filter_keys(assoc_name, assoc_attrs)).any?
  end

  def filter_keys(assoc_name, assoc_attrs)
    assoc_attrs.map { |attr_name| "#{assoc_name}_#{attr_name}".to_sym }
  end

  def conditions_from_params(assoc_name, *assoc_attrs)
    key_pattern = Regexp.new "\\A#{assoc_name}_(\\w+)\\z"
    item_filter_params.slice(*filter_keys(assoc_name, assoc_attrs)).transform_keys do |key|
      next $1.to_sym if key.to_s =~ key_pattern
      key
    end.to_unsafe_h
  end

  def sort_conditions_from_params(assoc_name, *assoc_attrs)
    associated_class = assoc_name.to_s.camelize.safe_constantize
    return unless associated_class.present?
    key_pattern = Regexp.new "\\A#{assoc_name}_(\\w+)_sort\\z"
    item_filter_params.slice(*sort_keys(assoc_name, assoc_attrs)).transform_keys do |key|
      next $1.to_sym if key.to_s =~ key_pattern
      key
    end.to_unsafe_h.map do |keyval|
      column_name, column_order = keyval
      associated_class.arel_table[column_name].send(column_order.to_sym)
    end
  end
end

app/views/home/show.html.slim
h1 Vovimayhem's ActiveRecord & Arel Crazy Stuff Demo

h2 Table of Contents

ul
  li
    = link_to 'Example using ActiveRecord::Base.from...', using_from_example_without_from_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArProTipsDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_logger_output.html.slim
section.rails-logger(id='active-logger' data-turbolinks-permanent='')
  header
    h2 Rails Logger Output
  
  ul.logger-output

app/views/using_from_example/_results_table.html.slim
section.items
  header
    h2 Fecthed Items:
  table.items
    thead
      tr.item
        th.id ID
        th.product Product
        th.category Category
        th.shelf Shelf
        th.rank Position from bottom
        th.properties Properties
    tbody
      - @items.each do |item|
        tr.item
          td.id = item.id
          td.product = item.product.name
          td.category = item.category.name
          td.shelf = item.shelf.name
          th.rank = item.shelf_rank
          td.properties Properties

app/views/using_from_example/with_from.html.slim
section.pro-tip
  header
    h1 Using `ActiveRecord::Base.from` Example
  section.intro
    p 
      span This is the example using the trick. Visit 
      = link_to 'the version not using the trick', using_from_example_without_from_path(item_filter_params)
  section.code-extract
    pre Some code extract
  = render 'results_table'
  = render 'shared/logger_output'

app/views/using_from_example/without_from.html.slim
section.pro-tip
  header
    h1 Using `ActiveRecord::Base.from` Example
  section.intro
    p 
      span This is the example using the trick. Visit  
      = link_to 'the version using the trick', using_from_example_with_from_path(item_filter_params)
  section.code-extract
    pre Some code extract
  = render 'results_table'
  = render 'shared/logger_output'